language: node_js
node_js:
  - "lts/*"
  - “8”

branches:
  only:
    - master

before_script:
  - npm install -g vue-cli
  - npm install firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
